### ISSUE TITLE
Input data format

### ISSUE THREAD

**Issue by kbrodt** [DanonOfficial/TGVDenoising#2]
Hi,

How to convert `.tif` files with float32 heights values to `.pfm`? Simple command `convert a.tif a.pfm` produces files with uint8 data type.

Thanks!

**Comment by HiddenTreasure525** [comment]
Hello!
I checked random file with .tif float values. According to GIMP convert command is working fine. Can you provide more information?

**Comment by kbrodt** [comment]
Can you please write a command to convert via gimp. I tried GUI with `export as` but it also saves as uint8

**Comment by HiddenTreasure525** [comment]
I used imagemagick `convert test.tif test.pfm`. And additionally tested in GIMP gui, I suppose you have problem with original image

**Comment by kbrodt** [comment]
My bad, I opened it via cv2.imread without flag -1. Now it's ok. Thanks!

Now I tried to run the program and get

```
> ./TGV -c -n 400 -p "data" -a "0" -r "resultFileName" -i 14
Using CPU
Amount of iterations: 400
Iteration # 300 out of 400
double free or corruption (!prev)
Aborted (core dumped)
```

and optimized image looks [weird](http://0x0.st/-90B.png) (upper triangle is ok, but lower is not). It's values also uint8, not in heights.

**Comment by HiddenTreasure525** [comment]
Ok, this is more interesting, I will take a look, but not earlier then weekend. Right now you can use the one in jupiter notebook, it is slower, but still working

**Comment by kbrodt** [comment]
Thanks! jupyter works fine. I rewrote it in torch using cuda and get the following performance

```
100%|██████████| 2000/2000 [01:45<00:00, 18.89it/s]
```

This is done for tiles with resolution 2048x2048 float32 height map and 8 observations. If it's comparable with your implementation so I'll use code from jupyter.
